all: mygame

mygame: Sample_GL3_2D.cpp glad.c
	g++ -o mygame Sample_GL3_2D.cpp glad.c -framework OpenGL -lglfw -lftgl -lSOIL -I/usr/local/include/freetype2 -I/usr/local/include -L/usr/local/lib

clean:
	rm mygame
